# Configuration for xygeni secrets scanner.
# Arguments from command line have priority over properties in this file.

# Includes: list of glob patterns to include in analysis.
#
# A pattern could use ** (to match zero or more directories), * (zero or more characters
# in a directory or file name), and ? (one character).
# Examples: **/*.txt matches all files with 'txt' extension. **/test/** matches all files under any test directory.
#
# If empty, ALL files will be matched.
# The command-line argument -i or --include will be used when specified.
#
# A file is analyzed when matched by 'includes' AND NOT matched by 'excludes'.
includes: []

# Filesystem excludes: list of glob patterns to exclude from analysis in a filesystem directory scan.
# If empty, NO file will be excluded.
# The command-line argument -e or --exclude will be used when specified.
excludes:
  # Documentation should be excluded
  - "**/docs/**/*"
  - "**/documentation/**/*"
  - "**/*.md"
  - "**/*.rst"
  - "**/*.doc"
  - "**/*.docx"
  - "**/*.odt"
  - "**/*.pdf"

  # Dictionaries and localization files
  # i18n typically does not contain secrets
  - "**/*.dic"
  - "**/*.dict"
  # java i18n
  - "**/messages.properties"
  - "**/messages_*.properties"
  - "**/i18n/**/*"
  # react-i18next
  - "**/public/locales/*/translation.json"
  - "**/LC_MESSAGES/django.po"
  # Android
  - "**/values/strings.xml"
  - "**/values-*/strings.xml"
  # gettext, lokalise
  - "**/*.po"
  - "**/*.pot"
  # OASIS XLIFF
  - "**/*.xlf"

  # Test directories should not be excluded in general, they can contain leaks
  #- "**/test/**/*"
  #- "**/tests/**/*"
  #- "**/mock/**/*"
  #- "**/mocks/**/*"
  #- "**/integration/**/*"

  # Exclude .git directories, but do not ignore config and other files with leaks
  - 'regex:(^|/)\.git/[^/]+/'
  - 'regex:(^|/)\.git/(?:index|packed-refs|FETCH_HEAD)$'

  # Generated/build directories should not be analyzed
  #- ".vscode/**/*"
  - "build/**/*"
  - "dev/**/*"
  - "**/target/**"

  - "**/__pycache__/**/*"
  - "**/.eggs/**/*"
  - "**/locales/**/*"
  - "**/spec/**/*"
  - "**/specs/**/*"
  - "**/package-lock.json"
  - "**/package.json"
  - "**/npm-shrinkwrap.json"
  - "**/node_modules/**/*"
  - "**/bower_components/**/*"
  - "**/vendor/**/*.php" # Composer
  - "**/lang/*/*.php" # i18n in PHP apps
  - "**/.phpstorm.meta.php"
  - "**/api-2.json.php"

  # Baseline files
  - "**/.xygeni.*.baseline.json"
  - "**/.xygeni.*.checksums.json"

  - "**/dist/**"
  - "**/*.log"
  - "**/*.min.js"

# History excludes: list of glob patterns to exclude from history scans.
# If empty, NO file will be excluded.
# The command-line argument -e or --exclude will be used when specified.
historyExcludes:
  # History files that should not be analyzed
  # i18n typically does not contain secrets
  # java i18n
  - "**/messages.properties"
  - "**/messages_*.properties"
  - "**/i18n/**/*"
  # react-i18next
  - "**/public/locales/*/translation.json"
  - "**/LC_MESSAGES/django.po"
  # Android
  - "**/values/strings.xml"
  - "**/values-*/strings.xml"
  # gettext, lokalise
  - "**/*.po"
  - "**/*.pot"
  # OASIS XLIFF
  - "**/*.xlf"

  # Dictionaries and localization files
  # i18n typically does not contain secrets
  - "**/*.dic"
  - "**/*.dict"

  - "**/*.log"
  - "**/*.min.js"
  - "**/target/**"
  - "**/dist/**"

# excludes for image scans: list of glob patterns to exclude from image scans,
# in addition to excludes for filesystem scans.
imageExcludes:
  - 'bin/**'
  - 'sbin/**'
  - 'lib/**'
  - 'lib32/**'
  - 'lib64/**'
  - 'usr/bin/**'
  - 'usr/sbin/**'
  - 'usr/lib/**'
  - 'usr/lib32/**'
  - 'usr/lib64/**'
  - 'usr/libexec/**'
  - 'usr/local/bin/**'
  - 'usr/local/sbin/**'
  - 'usr/local/lib/**'
  - 'usr/local/libexec/**'
  - 'usr/local/share/**'
  - 'usr/share/**'
  - 'etc/nsswitch.conf'
  - 'etc/shadow'
  - 'opt/python*/venv/lib/python*/site-packages/**'
  - 'var/lib/rpm/rpmdb.sqlite'
  - 'boot/**'
  - 'System/**'
  - 'Library/**'

# Ignore lines matching the given regular expression
ignoreLines: >-
  YOUR_REGEX_HERE

# Ignore secrets matching the given regular expression
ignoreSecrets: >-
  YOUR_REGEX_HERE

# Word to use in comments to be ignored (same line or at previous line)
# When empty, inline suppressions are not allowed
suppressToken: xygeni-secrets-allowed

# mode=sequential runs analyzers sequentially;
# mode=parallel runs analyzers in multiple threads, when analyzer is capable of parallel runs.
mode: parallel
#mode: sequential

# Parallelism specification (when mode=parallel):
# 'auto', 'sequential', a number N, or one of 'availableProcessors + N',
# 'availableProcessors - N', 'availableProcessors * N', 'availableProcessors / N'
# 'auto' means 'availableProcessors - 1', 'sequential' means 1
# 'min(v1, v2)' means the minimum between the two values.
# For example, 'min(availableProcessors - 1, 4)' is 4 if the number of cores is greater than 4, or cores - 1 otherwise.
parallelism: auto
#parallelism: min(availableProcessors - 1, 4)

# Timeout, in seconds, for the secrets scan to complete. 0 or negative means no timeout.
timeout: 3600

# Timeout, in seconds, for the history analysis to complete. 0 or negative means no timeout.
timeoutHistory: 2400

# Timeout, in seconds, for the secrets san on images to complete. 0 or negative means no timeout.
timeoutImage: 2400

# Timeout, in seconds, for processing a file for secrets. 0 or negative means no timeout.
fileTimeout: 180

# Enable analysis in commit messages (--history mode).
commitMessages: yes

# Commit resolution policy. One of: 'always', 'never', 'auto'.
# 'auto' means that commit info is disabled if too many findings are reported. For benchmarking projects, commit resolution can be disabled.
# 'never' means that commit resolution is disabled. No commit info (author, timestamp, commit ID and branch) will be reported.
# 'always' means that commit resolution is enabled unconditionally.
commitResolution: never

# Ignore verifications that call to external services.
# The --no-verify command-line option will be used when specified.
noVerify: no

# Report only verified secrets when there is a verifier available.
# For detectors without verifier, secrets discovered will be reported.
# The --only-verified command-line option will be used when specified.
verifiedOnly: no

# Is obfuscation enabled? If true or yes, --no-obfuscate can be used to disable obfuscation.
# Note that if obfuscation is disabled, the secrets report will not be uploaded for security reasons.
obfuscate: yes

# Is auto remediation enabled? If true or yes, --auto-remediate can be used to trigger auto remediation.
# Set to false if you want to disable auto remediation.
# This is useful if you want to remediate secrets manually, or only via web UI or automation workflow.
autoRemediationEnabled: yes

# Config for reporters
report:

  - format: json
    prettyPrint: true

  - format: sarif
    prettyPrint: true

  - format: csv

    # Allowed values: secret, secretId, hash, type, severity, confidence, key, resource, detector, file, beginLine, endLine, code, tags
    #columns: [ "severity", "type", "secret", "secretId", "hash", "key", "resource", "detector", "file", "beginLine", "endLine", "confidence", "tags"]
    columns: [
      "severity", "description", "secret", "key", "file", "beginLine", "endLine",
      "detector", "confidence", "type", "code", "resource", "secretId", "secretUrl",
      "commit", "user", "exposure", "tags"
    ]

    # Order specification. 'default' lists highest severe first, then by type, file and line.
    # One of 'default', 'type', 'exposure' or 'severity-confidence'. Blank for no sort
    sort: default

  - format: text

    # Allowed values: secret, hash, type, severity, confidence, key, resource, detector, file, beginLine, endLine, code, tags
    #columns: [ "severity", "type", "secret", "secretId", "key", "detector", "file", "beginLine", "tags"]
    columns: [ "severity", "description", "secret", "key", "file", "beginLine", "tags" ]

    # Order specification. 'default' lists highest severe first, then by type, file and line.
    # One of 'default', 'type', 'exposure' or 'severity-confidence'. Blank for no sort
    sort: default

    # The style for table borders.
    # One of 'full', 'none', 'outside', 'inside', 'horizontal', 'vertical', 'topbottom'.
    # Use 'default' for border that works well for the underlying OS.
    borders: full

    # The block characters to use: 'ascii' (use '+', '|', '-' and '=')
    # or 'utf8' for UTF-8 block characters.
    # Use 'default' for the encoding that works best for the underlying OS.
    bordersEncoding: utf8

# The detectors to use for detecting hard-coded secrets
# are configured in resource files under secrets/*.yml

# List of detectors to run: IDs or severity.
# runDetectors: ['high'] will run all detectors with severity 'high' or greater.
# runDetectors: ['aws-id', 'aws-secret', 'aws-token', 'github-token'] will run these.
# Leave empty for no restriction (all detectors not disabled will be chosen).
# Command-line property --detectors overrides this.
runDetectors: []

# Same format as runDetectors, but for skipping the selected detectors.
# skipDetectors: ['high'] will skip all detectors with severity 'high' or lower.
# Leave empty for no restriction (all detectors not disabled will be chosen).
# Command-line property --skip-detectors overrides this.
skipDetectors: []
